# Generated by Django 4.2.16 on 2024-12-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Farmer'), (2, 'FarmAgent'), (3, 'VeterinaryPartner')], null=True),
        ),
    ]
