# Generated by Django 4.2.16 on 2024-12-28 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_farmer_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Farmer'), (2, 'FarmAgent'), (3, 'VeterinaryPartner'), (4, 'FarmWorker')], null=True),
        ),
        migrations.CreateModel(
            name='FarmWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_contact', models.CharField(max_length=15)),
                ('employment_date', models.DateField(default=django.utils.timezone.now)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='user_management.farmer')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
