# Generated by Django 4.2.16 on 2025-01-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_user_user_type_farmworker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmagent',
            name='identification_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
