# Generated by Django 4.2.16 on 2024-12-19 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supply_chain', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmersupply',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.farmer'),
        ),
        migrations.AddField(
            model_name='farmersupply',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_chain.product'),
        ),
        migrations.AddField(
            model_name='farmerorder',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.farmer'),
        ),
        migrations.AddField(
            model_name='farmerorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_chain.product'),
        ),
        migrations.AddField(
            model_name='farmerinventory',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.farmer'),
        ),
        migrations.AddField(
            model_name='farmerinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_chain.product'),
        ),
    ]
