# Generated by Django 4.2.16 on 2025-01-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimalBreed',
        ),
        migrations.RenameField(
            model_name='animalprofile',
            old_name='name',
            new_name='animal',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='cow_tag',
        ),
        migrations.AddField(
            model_name='livestock',
            name='animal_type',
            field=models.CharField(choices=[('cow', 'Cow'), ('goat', 'Goat'), ('camel', 'Camel'), ('sheep', 'Sheep'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='livestock',
            name='breed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='other_animal_type',
            field=models.CharField(blank=True, help_text="Specify if 'Other' is selected", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='tag',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='animal_photos/'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='uploaded_document',
            field=models.FileField(blank=True, null=True, upload_to='animal_docs/'),
        ),
    ]
