# Generated by Django 4.2.16 on 2024-12-18 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_management', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='farmer',
            field=models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to='user_management.farmer'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.livestock'),
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.livestock'),
        ),
    ]
