# Generated by Django 4.2.16 on 2025-01-05 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_delete_animalbreed_rename_name_animalprofile_animal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='healthrecord',
            old_name='animal',
            new_name='livestock',
        ),
        migrations.RemoveField(
            model_name='animalprofile',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='animal_type',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='other_animal_type',
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='livestock',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='data_management.livestock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livestock',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('date_given', models.DateField()),
                ('administered_by', models.CharField(blank=True, max_length=100, null=True)),
                ('next_vaccination_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='data_management.livestock')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='data_management.livestock')),
            ],
        ),
        migrations.CreateModel(
            name='DeathRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_death', models.DateField()),
                ('cause_of_death', models.CharField(blank=True, max_length=200, null=True)),
                ('disposal_method', models.CharField(blank=True, max_length=100, null=True)),
                ('livestock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='death_record', to='data_management.livestock')),
            ],
        ),
        migrations.CreateModel(
            name='BreedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeding_date', models.DateField()),
                ('expected_birth_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dam_of', to='data_management.livestock')),
                ('offspring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_of', to='data_management.livestock')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sire_of', to='data_management.livestock')),
            ],
        ),
        migrations.AddField(
            model_name='livestock',
            name='livestock_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_management.livestocktype'),
            preserve_default=False,
        ),
    ]
