# Generated by Django 4.2.16 on 2024-12-14 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
        ('data_management', '0002_animalbreed_animalprofile_feed_healthrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='farmer',
            field=models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to='user_management.farmer'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cow_photos/'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='uploaded_document',
            field=models.FileField(blank=True, null=True, upload_to='cow_docs/'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.livestock'),
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.livestock'),
        ),
    ]
