# Generated by Django 4.2.16 on 2025-01-05 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_livestocktype_rename_animal_healthrecord_livestock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestock',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='uploaded_document',
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='breed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2025, 1, 5)),
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='animal_photos/'),
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='uploaded_document',
            field=models.FileField(blank=True, null=True, upload_to='animal_docs/'),
        ),
        migrations.AlterField(
            model_name='animalprofile',
            name='date_weighted',
            field=models.DateField(default=datetime.date(2025, 1, 5)),
        ),
    ]
