# Generated by Django 4.2.16 on 2025-01-05 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0006_remove_animalprofile_livestock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalprofile',
            name='livestock_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.livestocktype'),
        ),
    ]
