# Generated by Django 4.2.16 on 2025-01-06 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0007_alter_animalprofile_livestock_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalprofile',
            name='livestock_type',
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='livestock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_management.livestock'),
        ),
    ]
