# Generated by Django 4.2.16 on 2025-01-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0009_remove_animalprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalprofile',
            name='document_upload',
            field=models.FileField(blank=True, null=True, upload_to='animal_profiles/documents/'),
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='name',
            field=models.CharField(default='New', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='animal_profiles/photos/'),
        ),
    ]
