# Generated by Django 4.2.16 on 2025-01-14 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0011_animalprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkproduction',
            name='animal_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='milk_productions', to='data_management.animalprofile'),
            preserve_default=False,
        ),
    ]
