# Generated by Django 4.2.16 on 2025-01-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0012_milkproduction_animal_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestock',
            name='date_of_birth',
        ),
    ]
